### ISSUE TITLE
Hekate in pack not compatible

### ISSUE THREAD

**Issue by gehit22944** [THZoria/AtmoPack-Vanilla#14]
Hi, the Hekate in the newest Atmopack is not compatible with HOS 13.2.1 (https://github.com/CTCaer/hekate/issues/699) a new update is coming later today, but I'm wondering if Atmopack will be updated to reflect that, or if we should download the newest AtmoPack, wait for Hekate update and then just update it ourselves?

I'm unsure as to how I should do the latter, and update it myself, so if I have to do that, could you tell me how?
Thanks for AtmoPack. Makes things much easier for someone not as computer competent as myself. :)

**Comment by gehit22944** [comment]
Btw, just take your time to answer and/or update. I'm in no hurry whatsoever, just curios. :)

**Comment by THZoria** [comment]
AtmoPack has been updated with Hekate 5.7.0
This should correct the start of Atmosphere in 13.2.1

**Comment by gehit22944** [comment]
Thank you very much!
