### ISSUE TITLE
Hekate typo

### ISSUE THREAD

**Issue by conquelicot** [THZoria/AtmoPack-Vanilla#17]
Hi, here https://github.com/THZoria/AtmoPack-Vanilla/releases/tag/v2.2.2 and here https://github.com/THZoria/AtmoPack-Vanilla/releases/tag/v2.2.1 Hekate has been updated to 5.8.0 in the title but it is still 5.7.2 in the grey description box. I don't know where that grey box is located in the code, otherwise I would've just fixed it for you and sent a pull request. Just thought you should know and I wish you a good day. :)

**Comment by THZoria** [comment]
Hello

Thank you for the information, simple oversight ^^
It's edited, thanks.
