### ISSUE TITLE
Pack Atmosphere 1.4.0 Hekate 5.9.0 & Sigpatch FW 15.0.0 Bug?

### ISSUE THREAD

**Issue by dragon2snow** [THZoria/AtmoPack-Vanilla#20]
system: 15.0
switch v1

Install XCI of the newly released game,

Using DBI, the installation prompt is successful

But the game has unlimited loading icons

Unable to start, detection data is corrupt

Degraded to 14.1.2

The installation is successful and can be executed

I tested two switch, both of which are the results

**Comment by PoloNX** [comment]
Try with another nsp

**Comment by dragon2snow** [comment]
替换签名补丁解决问题了
这个包里的签名补丁安装所有游戏14以上的游戏失败

**Comment by dragon2snow** [comment]
替换签名补丁解决问题了
这个包里的签名补丁安装所有游戏14以上的游戏失败
