### ISSUE TITLE
Cant update to version 2.3.2

### ISSUE THREAD

**Issue by alaa007** [THZoria/AtmoPack-Vanilla#22]
Hello

Im on version 2.3.1 and when I try to update to version 2.3.2 using the AtmoPackUpdater v1.6.0, I go through the whole process from downloading, installing and restarting the console to see I'm still on version 2.3.1

I tried more than once and its not working.

Thank you for the great job :)

**Comment by PoloNX** [comment]
Hi, 

In fact your pack was updated. But zoria forgot to change the version in the file version.txt. 
I will say him to change this.

**Comment by alaa007** [comment]
You are right.

Thanks :)

**Comment by THZoria** [comment]
The version.txt problem is fixed
