### ISSUE TITLE
Latest release 2.4.5a includes Atmosphere 1.5.3 instead of 1.5.4

### ISSUE THREAD

**Issue by jamesst20** [THZoria/AtmoPack-Vanilla#27]
Hi,

I just installed your latest pack on my SD card and booted it, and in Settings -> Version it says "16.0.3| AMS 1.5.3|E"

The pack says it's including 1.5.4 version.

May I ask if there is a mistake?

Thank you!
Otherwise, everything is flawless!

**Comment by THZoria** [comment]
version.txt fix
thanks
