### ISSUE TITLE
Can't boot stock

### ISSUE THREAD

**Issue by Entretoize** [THZoria/AtmoPack-Vanilla#29]
I would like to acces the Nintendo shop and am trying to boot to sysnand.
So I added that in the hekate_ipl.ini:

[SYSCFW]
fss0=atmosphere/package3
stock=1
emummc_force_disable=1
icon=bootloader/res/icon_switch.bmp

but that result in the following errors:

```
Unknown pkg1 version.
HOS version not supported!

Tryning backup bootloader...
Found pkg1 ('').

Unknown pkg1 version.
HOS version not supported!

Failed to launch HOS!
```

Is there another solution ?

**Comment by THZoria** [comment]
Hello, there is a reboot option in Hekate, you can choose OFW or RCM.

**Comment by Entretoize** [comment]
Oh, ok, cool sorry I didn't know... But I get a black screen, what does
that mean ?

**Comment by THZoria** [comment]
I invite you to try again with version 2.6.0 of the pack just released, which should solve all your problems.
