### ISSUE TITLE
Sigpatch issue with the latest update

### ISSUE THREAD

**Issue by scummboy** [THZoria/AtmoPack-Vanilla#33]
When I installed the latest update (Pack Atmosphere 1.6.1 Hekate 6.0.7 & Sigpatch FW 17.0.0) none of my installed games would work, even after running the Update Sigpatches in the AtmoPack homebrew app. I had to roll back to firmware 16.1.0 and the previous Atmosphere (1.5.5) and Hekate (6.0.5) to get anything to work again.

Was I doing something wrong? It seems like the sigpatches _should_ have worked on inital upgrade.

**Comment by THZoria** [comment]
I had updated the pack yesterday, perhaps for this reason, I regenerated and put back online the pack, I invite you to test again

**Comment by scummboy** [comment]
Hello,

Thank you for your reply. I had installed it just prior to posting the issue, so it would have been the updated version.

**Comment by THZoria** [comment]
Yes, I don't like to give the possibility to start easily in sysNAND so I updated the config allowing it in more config, I think it's on this fix that I had a problem with patches, anyway I asked the member of my discord to update in the afternoon and according to their feedback it works correctly now.
Thanks for the report :)

**Comment by scummboy** [comment]
Thank you for the reply! I followed the update on the release:

> if you're having trouble with sigpatches, don't hesitate to delete the "kip_patches" and "exefs_patches" folders in the atmosphere folder and reapply the pack.

And once I did that it works again perfectly!
