### ISSUE TITLE
sifpatch folders are empty

### ISSUE THREAD

**Issue by wyndcrosser** [THZoria/AtmoPack-Vanilla#34]
Hello,

It looks like the sigpatch folder is empty. I'm guessing this is result of something that rhymes with Mintendo. Just checking.

Thanks.

**Comment by THZoria** [comment]
Problem solved, however, the next Atmosphere upgrade will no longer allow the use of ips fs from what I understand, wait and see but the use of iTotalJustice's sysmodule will be necessary I imagine.

**Comment by wyndcrosser** [comment]
THANKS

**Comment by Jajay22** [comment]
Hi I'm new to mod but I have download your pack 17.0.0 and install everything but once I boot to atmosphere or ofw it always appears to have error screen saying atmosphere err 10000000005 I don't know if I bricked my console because I can't even go in normal stock mode can u help or advise me

**Comment by wyndcrosser** [comment]
Not sure why I’m here.

You prob didn’t update correctly. See this page.


https://github.com/Atmosphere-NX/Atmosphere/issues/1177

**Comment by THZoria** [comment]
I don't know why you mention the AtmoPack-Vanilla on the Atmosphere github, who are against AIOs / Sigpatches.
As for sigpatches in general, no worries, it was retested on a hack-free switch today.

**Comment by Jajay22** [comment]
Sorry I think I did messed up my console not saying it's any body's fault but mine didn't do the research and did my own process and mess things up
